### ISSUE TITLE
Make OBS configuration more ergonomic

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/srcomp-mixtape#11]
would be great to:
- lose the hardcoding of the pre-transition delay
- transition out of the scene afterwards (maybe as its own "track"?)

**Comment by WillB97** [comment]
Would also be good to have the time defined for the `obs_video` action be the time the video played

**Comment by RealOrangeOne** [comment]
> lose the hardcoding of the pre-transition delay

https://github.com/srobo/srcomp-mixtape/pull/14

> transition out of the scene afterwards

https://github.com/srobo/srcomp-mixtape/pull/15
